Raise docker-py requirement to 4.x
ros-tooling/cross_compile pull request #259
Opened 2020-09-15 14:18 UTC by teodormadan

Signed-off-by: Teo Madan <teodor.madan@nxp.com>

2020-09-15 14:30 UTC, teodormadan commented
Compatibility has been addressed with https://github.com/ros-tooling/cross_compile/pull/237/, 

Still installing ros_cross_compile from source would bring older docker-py

2020-09-16 12:25 UTC, teodormadan commented
Handled also the new BuildError 3.x docker API according to detected docker version, and remove the old test for BuildError api as not applicable.

2020-09-23 20:11 UTC, emersonknapp commented on setup.py
> +        'docker>=2,<5',
I've been thinking about upgrading this, the old version requirement is from an old situation that no longer applies. Perhaps we could just make this

```suggestion
        'docker==4.*',
```

2022-12-04 06:38 UTC, MichaelOrlov approved these changes

2022-12-04 07:40 UTC, MichaelOrlov requested changes
@teodormadan @emersonknapp CI jobs for MacOS fails with this PR.
Please help to fix.

2022-12-07 02:15 UTC, closed without merging